name: Sync LeetCode to Notion and Update README

on:
  push:
    paths:
      - "Problems/**/*.md"
      - ".github/workflows/notion-sync.yml"
      - "notion_sync.py"
      - "update_readme.py"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies for Notion sync
      - name: Install dependencies
        run: pip install requests

      # Run Notion Sync
      - name: Run Notion Sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python notion_sync.py

      # Update README with problem list
      - name: Update README.md
        run: python update_readme.py

      # Commit changes using GITHUB_TOKEN
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with problem list"
          git push